version: '3.8'

services:
  web:
    build: .
    image: subscription-manager:${BUILD_NUMBER:-latest}
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=subscription_management.settings
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_DEBUG=0
    volumes:
      - static_volume:/app/static
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A subscription_management worker -l info
    environment:
      - DJANGO_SETTINGS_MODULE=subscription_management.settings
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis

volumes:
  static_volume:
