version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=subscription_management.settings
      - DJANGO_DEBUG=1
    volumes:
      - .:/app
      - static_volume:/app/static
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  static_volume:
