version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./deployment/nginx:/etc/nginx/conf.d
      - ./deployment/certbot/conf:/etc/letsencrypt
      - ./deployment/certbot/www:/var/www/certbot
      - static_volume:/app/static
    depends_on:
      - web

  web:
    image: subscription-manager:${BUILD_NUMBER:-latest}
    expose:
      - "8000"
    environment:
      - DJANGO_SETTINGS_MODULE=subscription_management.settings
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_DEBUG=0
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
    volumes:
      - static_volume:/app/static
    depends_on:
      - redis

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data

  celery:
    image: subscription-manager:${BUILD_NUMBER:-latest}
    command: celery -A subscription_management worker -l info
    environment:
      - DJANGO_SETTINGS_MODULE=subscription_management.settings
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis

volumes:
  static_volume:
  redis_data:
