# Generated by Django 5.1.4 on 2024-12-13 07:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('entertainment', 'Entertainment'), ('utility', 'Utility'), ('software', 'Software'), ('other', 'Other')], default='other', max_length=20)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subscription_date', models.DateField()),
                ('renewal_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10)),
                ('next_due_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
