# Generated by Django 5.1.7 on 2025-04-01 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_subscription_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('created', 'Subscription Created'), ('renewed', 'Subscription Renewed'), ('paid', 'Payment Made'), ('modified', 'Subscription Modified')], max_length=20)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='subscriptions.subscription')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
